<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class DiscountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//        $discounts = [
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Cambios',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 5,
//                'active' => true,
//                'region_id' => 2,
//                'brand_id' => 1,
//                'access_type_code' => 'C',
//            ],
//            [
//                'name' => 'Inauguración',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 50,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 3,
//                'access_type_code' => 'A',
//            ],
//            [
//                'name' => 'Recurrente',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 30,
//                'active' => false,
//                'region_id' => 3,
//                'brand_id' => 3,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Cumpleaños',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 80,
//                'active' => true,
//                'region_id' => 4,
//                'brand_id' => 2,
//                'access_type_code' => 'C',
//            ],
//            [
//                'name' => 'Finde',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 5,
//                'active' => false,
//                'region_id' => 2,
//                'brand_id' => 3,
//                'access_type_code' => 'A',
//            ],
//            [
//                'name' => 'Maravilla',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 18,
//                'active' => true,
//                'region_id' => 2,
//                'brand_id' => 3,
//                'access_type_code' => 'A',
//            ],
//            [
//                'name' => 'Promo',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 40,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 2,
//                'access_type_code' => 'C',
//            ],
//            [
//                'name' => 'Fantasia',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 12,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 3,
//                'access_type_code' => 'A',
//            ],
//            [
//                'name' => 'Unidad',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 33,
//                'active' => false,
//                'region_id' => 2,
//                'brand_id' => 3,
//                'access_type_code' => 'C',
//            ],
//            [
//                'name' => 'Nuevo',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 18,
//                'active' => true,
//                'region_id' => 4,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Libro',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 21,
//                'active' => false,
//                'region_id' => 4,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Almohada',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 12,
//                'active' => true,
//                'region_id' => 4,
//                'brand_id' => 1,
//                'access_type_code' => 'C',
//            ],
//            [
//                'name' => 'Viaje',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Remate',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 33,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//            [
//                'name' => 'Primavera',
//                'start_date' => Carbon::today(),
//                'end_date' => Carbon::tomorrow(),
//                'priority' => 15,
//                'active' => true,
//                'region_id' => 1,
//                'brand_id' => 1,
//                'access_type_code' => 'F',
//            ],
//        ];
    }
}
